language: java
# Disabling sudo routes the build to Docker instead of a VM which is faster.
sudo: false

addons:
  apt:
    packages:
      - libcommons-codec-java
      - junit4

matrix:
  include:
    - jdk: openjdk7
      dist: trusty # Java 7 is only available there.
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk13

script:
  - set -o errexit
  - gradle clean test jar
  - sha256sum -b build/libs/checkpoint.jar
